### ISSUE TITLE
写真撮影の手配

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#11]
- [ ] 業者を手配？（各社の有志で済ます？）
- [ ] 撮影用の腕章とかいる？

**Comment by ahomu** [comment]
あ、写真撮影のこと忘れてた。
どうしましょね。写真が得意な各社スタッフがいれば手っ取り早いですが。

**Comment by basara669** [comment]
弊社に公式カメラ隊ってのがあるんで、ちょっと聞いてみます〜

**Comment by ahomu** [comment]
公式カメラ隊！おねがいしますー。

**Comment by ahomu** [comment]
公式カメラ隊は出動しそうですか？
後日、各社の広報が使ったり使わなかったりすると思うので写真データをどっかで共有できるといいですね。（関係者が勝手に撮ったやつも含めて）

**Comment by basara669** [comment]
カメラ隊確定しました〜！

**Comment by ahomu** [comment]
お好きなタイミングで close していただければ :pray:
手配内容の詳細について issue か、パブリックに書くのがはばかれる場合は docs とかに残していただけると次回に良いかもしれませぬ！
