### ISSUE TITLE
キンコーズ案件の整理

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#12]
制作したいもの
=====

- ステッカー（ロゴ素材を直入稿で何とかなるハズ）
- スタッフTシャツ（あると中の人たちが嬉しい）
- タイムテーブル（ちゃんと作るとかっこいい）
- セッション/ブースごとの部屋の入り口にはる掲示物（ 14:00〜14:30 ほげほげセッション ）みたいな
- 腕章 → ヤフーさんのものをお借りできる？
- 参加証（ちゃんと作るとかっこいい）

などなど。必要に応じて別 issue に切り出し。

**Comment by ahomu** [comment]
@basara669 @studiomohawk 
最低限 ↑ のチェックが付いている項目は用意したほうが良いかなと思うのですがどうでしょう？

プレス用、撮影用の腕章とかは、イベント用で手作りしなくてもヤフーさんにあったりしますかね...？

**Comment by studiomohawk** [comment]
会場内の部屋にタイムテーブルな紙つける。
くらいが最低限ではないかと。。。
あとはおまけでしょ。

**Comment by ahomu** [comment]
ステッカーはほら、PCに貼って欲しいじゃないですか、運良く2回目以降を開催できたときのためにもｗ
（と、ロゴデータだけでいいから入稿までの手間がほとんどなくラクチン

**Comment by basara669** [comment]
ステッカーとスタッフTシャツ欲しいですよねｗ

**Comment by ahomu** [comment]
と、参加証は同日に会場で他のイベントも開催されてるとかの話があったので、識別子あったほうがよいかなと。

**Comment by basara669** [comment]
撮影用腕章はある気がしますね〜

**Comment by studiomohawk** [comment]
貧乏症だから。。。
あったらいいなで見積りしてお財布と相談するが正解な気がする。

**Comment by ahomu** [comment]
- ステッカー（ロゴ素材を直入稿で何とかなるハズ）
- スタッフTシャツ（あるとかっこいい）
- タイムテーブル（ちゃんと作るとかっこいい）
- セッション/ブースごとの部屋の入り口にはる掲示物（ 14:00〜14:30 ほげほげセッション ）みたいな
- 腕章 → ヤフーさんのものをお借りできる？
- 参加証（ちゃんと作るとかっこいい）

**Comment by basara669** [comment]
（弊社の予算で…

**Comment by studiomohawk** [comment]
デザインを作るのはとてもイヤだ。。。

**Comment by ahomu** [comment]
自分の周りだとキンコーズさんをよく使うのですが、ヤフーさんのほうでよく使う業者ありますか？（どこに見積もりを出そうか的な）

**Comment by basara669** [comment]
弊社もキンコーズですね！

**Comment by ahomu** [comment]
奇遇！では詳細を詰めたらキンコーズさん見積もりで大丈夫そうですね。

**Comment by shibe97** [comment]
connpassで募集なら、よしこさん作の「参加者の名は」使えそうですね。
https://yoshiko-pg.github.io/your-name/

**Comment by basara669** [comment]
コレもcloseしてOK？

**Comment by becyn** [comment]
closeして大丈夫そうです！
