### ISSUE TITLE
FOR_STAFF.md の作成

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#13]
https://github.com/insidefrontend/issue-1/blob/master/backyard/FOR_STAFF.md の中身を詰める

**Comment by basara669** [comment]
更新しました〜

**Comment by ahomu** [comment]
@basara669 
ありがとうございます！ ~あと、👇あたり追記しようかと思います。~ 明日現地で打ち合わせるようにします！

- 開始案内後の大部屋1つから部屋2つに分けるタイミングとオペレーション
- 最終セッションのあと、アンケートに答えてもらうときのオペレーション
- 終了挨拶前の部屋2つを大部屋1つに戻すタイミングとオペレーション

部屋を分けたり繋いだりする実作業的なのは、Y! のスタッフ各位に現地で指示していただけるイメージで大丈夫でしょうか？（READMEに手順詳細書くようなものではないですよね的、一応の確認）

**Comment by basara669** [comment]
ギリギリな感じではありましたが、無事終わったので閉じます〜
