### ISSUE TITLE
ケータリングの手配

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#14]
出ていた案
=====

- [ ] おやつ
- [ ] スタバポットサービスほかドリンク
- [ ] フィンガーフード

**Comment by basara669** [comment]
今朝軽く打ち合わせ話した時のメモ

### 懇親会
- 美登利寿司（もしくはお寿司 😢 ）
- ピザ
- おかずっぽいやーつ（UBER EATSで良い感じのあれば、それで）
- お酒
- ソフトドリンク

### AMAなど
- お菓子
- スタバのポット

### 出演者向け
- お弁当

### 食べ物以外で終日あったほうが良さそうなもの
- コップとかお皿
- ティッシュ
- ゴミ袋
- ウェットティッシュ

### 何気にハードルが高そうなもの
- ヤフー水

**Comment by ikuty55** [comment]
@ahomu @ueki824 
イベント準備担当の中西です。
ケータリングの数決めの参考にしたいので教えていただきたいのですが、
AbemaDevConfでは、参加者何人で、懇親会には何人参加されていましたでしょうか？

**Comment by basara669** [comment]
懇親会時の机のレイアウトも考えておきたいすな〜

**Comment by hiloki** [comment]
（弊社のサービスをこっそり置いときますね）
http://goody-apt.jp/

**Comment by ahomu** [comment]
@ueki824 

https://github.com/insidefrontend/issue-1/issues/14#issuecomment-273986395
こちら当日の実態数を把握できていないのでご回答おまかせしますー。

**Comment by basara669** [comment]
@ikuty55 
とりあえず、松・竹・梅で軽く試算してもらっても良いですか？

松：懇親会（参加者）＋梅
竹：メンバーでの打ち上げ（お寿司、ピザ、お酒）＋梅
梅：コーヒー＋フィンガーフード＋お菓子

費用対効果的なところで考えようと思います。

**Comment by basara669** [comment]
これ終わったらここcloseする

[https://docs.google.com/spreadsheets/d/1vOp-k6G7iRtNOEwbz-ePb5kCVEacYdr_70uRfQlKe18/edit](https://docs.google.com/spreadsheets/d/1vOp-k6G7iRtNOEwbz-ePb5kCVEacYdr_70uRfQlKe18/edit)

**Comment by basara669** [comment]
無事終わったので終了。
け、経費精算がんばろう…
