### ISSUE TITLE
スタッフ向けケータリングの手配（をするか検討）

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#15]
対象者
=====

- [ ] セッションスピーカー
- [ ] AMA ブースオーナー
- [ ] ほかスタッフ

腹が減っては戦は出来ぬが、各自に任せても OK ？

**Comment by ahomu** [comment]
@basara669 会場ビルにコンビニありましたよね？（であれば、スタッフ向けお弁当とかはナシでもよいかな？と）

**Comment by basara669** [comment]
@ahomu ありますね〜！
スタッフ向けって余ったりするので、そのほうが良いかもですね〜

**Comment by ahomu** [comment]
おっしゃ、ナシで！ｗ
