### ISSUE TITLE
会場のインフラ確認

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#17]
確認事項
=====

- [x] 部屋の間取りとキャパシティ
- [x] Wi-Fi の有無とキャパシティ
- [x] 電源の有無と量（電源タップなどの別途調達を検討）

**Comment by basara669** [comment]
登壇者のみのwifiが難しそう…

**Comment by ahomu** [comment]
Wifiのキャパに不安があるようなら、ネットに接続が必要な登壇者はモバイルルーターの持参をお願いしておくほうが良さげ？(念のため)

**Comment by basara669** [comment]
たぶん設備的には400から500くらいまで平気なんですけど、念のため登壇するスペースには有線を置いておこうかと思います

**Comment by ahomu** [comment]
強靭な設備！ MacBook とかだと素直に有線刺せなさそうですが、USB変換アダプタとかですかね。

**Comment by basara669** [comment]
USB-cのがないかもしれないですね(´・ω・｀)
ちょっと探してみます。

**Comment by basara669** [comment]
## wifi
| SSID |パスワード |
|:-----------|:------------|
| WA-GN1  | zeroshinegi53 |

**Comment by basara669** [comment]
## 電源

- 電源タップはフリーアドレスになったせいかたくさんあるので調達は不要
- 会場の席には電源がついているわけではない
- 一部の席（例えば後ろ2列とか3列とか）電源タップを指すとかはできそう

**Comment by ahomu** [comment]
確認できてるの close
