### ISSUE TITLE
タイムテーブルを確定させる

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#19]
残タスク
======

- [x] 空き枠①と②の行方
  - ~~公募？~~
  - ~~特定の団体に預ける？~~
  - ~~候補にオファーする？~~
  - 削除
- [x] CA の未定セッションの確定
- [x] ヤフーの未定セッションの確定
- [x] 18:10-18:35 の謎枠の削除（空いた時間をセッションかブース運営の時間に分配する？）
- [x] 登壇者のテックリハやお昼ご飯の時間

**Comment by studiomohawk** [comment]
> 空き枠①と②の行方

要らない AKA Yahoo!様に預けるに1票。

**Comment by studiomohawk** [comment]
> 18:10-18:35 の謎枠の削除（空いた時間をセッションかブース運営の時間に分配する？）

要らないに1票。

**Comment by ahomu** [comment]
各社の採用ブースとして使い切るのもアリといえばアリ？
他のブースとの生存競争に勝てないか...w

**Comment by ahomu** [comment]
ヤフーとCAの未定セッションを埋めたら一旦固まったことになりそう。

<img width="1252" alt="screen shot 2017-01-12 at 15 23 22" src="https://cloud.githubusercontent.com/assets/404356/21879314/3f764afe-d8db-11e6-8c63-d197a56fa653.png">

**Comment by ahomu** [comment]
確定してるので close しますー。
