### ISSUE TITLE
告知用 Web ページの用意

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#5]
だれがつくるんだ...。 @hiloki さん...........。
開催の45〜30日前には公開したいところ。

**Comment by ahomu** [comment]
@hiloki @studiomohawk 実装も見た目も情報設計もすばらしい Web サイトにしてくれそうなお二方にアサインなげました！（よろしくおねがいします）

**Comment by hiloki** [comment]
スケジュール的にもう動かねばですな

**Comment by ahomu** [comment]
おつかれさまでした！とりあえず close します
