### ISSUE TITLE
FRESH 配信の手配

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#6]
- [x] 業者の手配
- [x] 番組の登録
- [x] 出演者に放送、録画の可否を確認

**Comment by ueki824** [comment]
▼歩さんに確認したいこと
・費用はどの程度までであればOKか
　┗稼働時間・ネット環境にもよるが15-20万くらいかかる

・ネット環境
　┗有線があれば◎、なければ参加者が使う全体wifi以外の線使う必要あり

・いつからライブ配信をアナウンスするか

**Comment by ueki824** [comment]
・現状当日のインターネット回線についてはbasaraさんに確認中
・業者手配については、FRESH CP局メンバーに相談したいが彼が本日インフルでお休みのため週明けに見積もりなど相談します

**Comment by basara669** [comment]
有線の回線使えるので、速度的にもOKだと思います！

**Comment by ueki824** [comment]
・セミナールーム見取り図が頂けそうかどうか、basaraさんにご相談中

**Comment by basara669** [comment]
見取り図もう少々お待ち下さい 🙇 🙇 🙇

**Comment by basara669** [comment]
見取り図やっとゲットしました！
slackに貼っておきます〜！

**Comment by ueki824** [comment]
依頼しているいつもの業者の方に再度お伺いするが返信無し（この業者が厳しくても、他候補もあるので問題ないとのこと）
来週月曜までに連絡がなければ、別業者さんに依頼するようFRESH担当に相談します

**Comment by ueki824** [comment]
レバテックさまという業者で決定、今当日いらっしゃる人数等確認中

**Comment by ueki824** [comment]
▼Seminar A
https://freshlive.tv/tech-conference/86340

▼Seminar B
https://freshlive.tv/tech-conference/86341

上記で番組登録完了、撮影NGの方もなしということで確認済み
業者の方が何名いらっしゃるか未定なので、まだこのissueは閉じずにいます

**Comment by ahomu** [comment]
うえきさんのタイミングで close していただいて OK です！
手配内容の詳細についてココか、Google Docs にでもドキュメント化されてると次回助かります :pray:

**Comment by ueki824** [comment]
@ahomu 
【FRESH！配信依頼フロー】

①配信代行業者はいつもFRESH！が依頼しているレステックさんにお願いした
　┗拘束時間と撮影会場数により費用は異なる（費用については別途slackにて）
　┗1か月前くらいにお願いすれば基本的には問題ない

②参加募集開始後、運営キーマンにも時期問題ないか確認したのちにFRESH！Tech Conferenceチャンネルにて番組登録を行い、公開する（今回は2週間前）
　　https://freshlive.tv/tech-conference
　┗サムネ画像（960px x 540px）、番組名（推奨50文字以内）、番組概要（1000文字以内）が必要

③公開後、各公式SNSアカウントで拡散を行う
　また登壇者に撮影NGの方がいないか確認、NGの方いる場合は業者さんにその旨をお伝えし、
　当日は該当時間は「配信不可のセッションです」といった扉絵をはさむ


④本番までに業者さんから確認依頼されたのは下記の通り

★会場のPA設備からラインがもらえるか、もらえない場合はガンマイクで音を拾う必要があるので音声のクオリティが悪くなる懸念あり

今回のヤフーさま本社セミナールームの会場の接続構成は下記の通りだったので音が良かった

> 端子盤　→　XLRケーブル　→　レベルコンバーター　→　RCAケーブル　→　LiveshellPRO

　┗基本どのセミナールームもこの構成が多いそう
　┗レベルコンバーターは、LiveshellPROがRCA入力しかないために使用しているが、
　　　XLRケーブルをそのまま接続できる配信機器であれば不要


★本番開始2時間前に入場可能かどうか

★セミナー会場の見取り図

★レステックが持っている民生機カメラを使用して良いかどうか（明るさの調整やフルマニュアルでの設定、音の入力など細かな調整が可能なため）
　┗FRESH！所有のカメラを使用するよりも少しコストが上がる

★有線が使えるかどうか
　┗参加者が使用するwifiを使うのは危険、映像が安定しなくなる



⑤当日
・レステックさんの配信準備は2時間あれば問題ない
・セッション開始時には登壇者とスクリーンを写し、セッションが始まったらスクリーンのみをアップで映す方法が良い
