### ISSUE TITLE
プレスの手配

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-1#7]
gihyo.jp など各種、テック系の Web 媒体との取材連携

**Comment by ueki824** [comment]
・似たようなレポート記事が複数掲載されるのも意味がないので、まずは gihyo.jp にしぼってお声掛けしてみようと思います。
AbemaTV DevConの際にも参加してくださった池田 大樹さんにお声がけ予定。

・できれば募集用connpassページ開設してすぐくらいのタイミングで、募集盛り上がりも合わせてお伝えする形でお声掛けしたい

@ahomu 
https://github.com/insidefrontend/issue-1/issues/9
上記を見ても開設タイミングわからなかったのですが、ページ開設って来週くらいのご予定でしょうか？

**Comment by ueki824** [comment]
・1/25周辺に集客開始のため、1/27(金)に池田さまにお声かけ
　┗1週間返信なければ、別媒体（ITproかITmediaあたり）にもお声かけさせていただく

**Comment by ueki824** [comment]
・技術評論社池田さまにお越しくださるとのこと、受付で名前を控えておく

**Comment by ueki824** [comment]
登壇者で写真NGの方をのちほど池田さんに共有する

**Comment by ueki824** [comment]
登壇者NG者無しの旨、池田さんに共有済み

**Comment by ahomu** [comment]
うえきさんのタイミングで close していただいて OK です！
手配内容の詳細についてココか、Google Docs にでもドキュメント化されてると次回助かります :pray:

**Comment by ueki824** [comment]
@ahomu 
当日の記者とのやりとりなども含めて書きたいとおもうので、のちほどまとめますね！

**Comment by ueki824** [comment]
@ahomu 
【InsideFrontend 記者さんご招待のフロー】

①このようなカンファレンスのレポート記事は複数媒体に掲載いただく必要性が強くないため、こちらで把握している技術媒体の中から、当カンファレンスに興味をもっていただけそうな技術評論社 池田さまのみにご連絡


②カンファレンスのお声かけは、参加応募を開始したあとの方がコミュニティにどのくらい注目いただいているか伝えられるので、今回も応募開始の翌日に下記のとおりご連絡

> お世話になっております。サイバーエージェント植木です。
> 先日はAbemaTV DevConをお取り上げいただき、ありがとうございました！
> 
> 来月当社とYahoo!さま、日経さまの3社で共同開催するフロントエンド系カンファレンスがあり、ぜひ取材いただけないかご相談したく、ご連絡させていただきました。
> 
> フロントエンド界隈で有名な技術者が多く登壇することもあって注目をいただいており、おかげさまで昨日夕方の応募開始から半日で定員の300人を突破しております。（現在375人の申し込みいただいています）
> 
> 
> Inside Frontend #1
> 2/25（土）13時~18時＠ヤフー株式会社 紀尾井タワー セミナールーム
> http://inside-frontend.com/
>
> 
> 
> 是非ご確認いただけますと幸いです。
> お忙しいところ大変恐縮ですが、どうぞよろしくお願いいたします！


③取材OKのご連絡いただいたら、当日はお名前を受付で言うだけで入場できる旨をお伝えする
　同時に受付担当メンバーにも会社名と氏名を伝えておく


④登壇者がFIXしたら、撮影/掲載NGの方がいないか確認
　その旨記者さんに事前にご連絡（本番1週間前にはご連絡）


⑤当日来場いただいてご挨拶した後のアテンド等は特になし
  基本的にカメラマンも兼ねておひとりで来られることが多い


⑥gihyo.jpには確実に掲載いただき、可能であれば4月末発売のWEB+DB PRESSにも掲載いただけるかもとのこと
技術評論社さまはありがたいことに公開前に事前に確認連絡をくださるので、各社広報と掲載されている登壇者や運営キーマンに問題ないか確認をいれる


⑦公開いただいたあとは公式Twitterでも拡散し、slackの #general でも周知する


【次回のTODO】
・今回はおひとりだったが、人数が多くなりそうであれば、プレス席を設けておくのもありかも？
